package br.edu.ifsp.model.enums;

public enum EspecialidadeEnum {

	CABELO_CORTE,
	CABELO_COLORACAO,
	CABELO_LUZES,
	CABELO_ALIZAMENTO,
	CABELO_RECONSTRUCAO,
	CABELO_PERMANENTE,
	CABELO_HIDRATACAO,
	CABELO_PINTURA,
	CORTE_BARBA,
	PERMANENTE_CILIOS,
	REPARO_SOBRANCELHAS,
	MAKE_UP,
	DEPILACAO,
	SPA_PARA_PES,
	SPA_PARA_MAOS	
}
